### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Muhammad-Mohsin-Raza**
Outline for MLSA League

### CODE REVIEW

**Review by Abdullah-Tahir — CHANGES_REQUESTED** [review]
can you send in .md format please?

**Comment by Muhammad-Mohsin-Raza** [comment]
new request

**Review by Abdullah-Tahir — CHANGES_REQUESTED** [review]
okay looks enough.

**Comment by EmberCodeEx** [comment]
[Research Process.docx](https://github.com/Abdullah-Tahir/Level_One/files/8172038/Research.Process.docx)

**Pull request merged**
